server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.129:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 192.168.200.129
  redis:
    host: 192.168.200.129

  main: # 因为在用SpringBoot的时候SpringBoot会加载一套Spring的配置，现在用SpringCliud也会加载一套Spring配置,所以在加载对象时加载了两次注解配置出现冲突 加载对象重复
    allow-bean-definition-overriding: true #允许配置同名对象，后加载的配置会覆盖之前的配置

    # JWT 规范单点登录
jwt:
  config:
    key: miyue # 密钥
    ttl: 3600000 #过期时间一小时

# 客户端注册到服务端的服务端地址
eureka:
  client:
    fetch-registry: true #是否从Eureka服务中获取服务列表信息
    registerWithEureka: true #是否将自己注册到Eureka服务中，现在为客户端所以为 true
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/  # 服务端地址 需和Eureka 服务中配置信息一直
  instance:
    prefer-ip-address: true # 注册时将服务所在的 ip 注册到服务列表，而不是主机名

