server:
  port: 9012
spring:
  application:
    name: tensquare-web #指定服务名

  main: # 因为在用SpringBoot的时候SpringBoot会加载一套Spring的配置，现在用SpringCliud也会加载一套Spring配置,所以在加载对象时加载了两次注解配置出现冲突 加载对象重复
    allow-bean-definition-overriding: true #允许配置同名对象，后加载的配置会覆盖之前的配置

eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:  #路由配置
    tensquare-qa: #自定义,可以指定为对应微服务名称
      path: /qa/** #配置请求URL的请求规则
      serviceId: tensquare-qa #指定Eureka注册中心中的服务id
    tensquare-base: #自定义,可以指定为对应微服务名称
      path: /base/** #配置请求URL的请求规则
      serviceId: tensquare-base #指定Eureka注册中心中的服务id
    tensquare-user: #自定义,可以指定为对应微服务名称
      path: /user/** #配置请求URL的请求规则
      serviceId: tensquare-user #指定Eureka注册中心中的服务id
    tensquare-friend: #自定义,可以指定为对应微服务名称
      path: /friend/** #配置请求URL的请求规则
      serviceId: tensquare-friend #指定Eureka注册中心中的服务id


