
server:
  port: 9001
spring:
  #此RabbitMQ 引用的是SpringCloud BUS 里的集成RabbitMQ 但是集成的跟SpringBoot的集成MQ用法一样
  rabbitmq:
    host: 192.168.200.129
  application:
    name: tensquare-base #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver  #com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.129:3306/tensquare_base?characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show‐sql: true
    generate‐ddl: true

  main: # 因为在用SpringBoot的时候SpringBoot会加载一套Spring的配置，现在用SpringCliud也会加载一套Spring配置,所以在加载对象时加载了两次注解配置出现冲突 加载对象重复
    allow-bean-definition-overriding: true #允许配置同名对象，后加载的配置会覆盖之前的配置

# 客户端注册到服务端的服务端地址
eureka:
  client:
    fetch-registry: true #是否从Eureka服务中获取服务列表信息
    registerWithEureka: true #是否将自己注册到Eureka服务中，现在为客户端所以为 true
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/  # 服务端地址 需和Eureka 服务中配置信息一直
  instance:
    prefer-ip-address: true # 注册时将服务所在的 ip 注册到服务列表，而不是主机名

##自定义配置
#zidingyi: haha



# # application.yml 文件代替了 application.yml
#   #在启动此服务时，此服务会去tensquare_config微服务去加载上传到Git上的base配置文件
# spring:
#   cloud:
#     config:          # Spring Cloud Config 组件，统一管理配置文件工具
#       name: base     # 文件名前段
#       profile: dev   #文件中断
#       label: master   #指定读取那个分支
#       uri: http://127.0.0.1:12000


